# Generated by Django 4.2.6 on 2023-12-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_quantite_produit_nombre_alter_client_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('sexe', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('antecedent', models.TextField(null=True)),
                ('prescription1', models.CharField(max_length=150, null=True)),
                ('prescription2', models.CharField(max_length=150, null=True)),
                ('prescription3', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
